site_name: City-level Transmission Toolkit
site_url: https://remyfp.github.io/CLT_BaseModel_Docs/
plugins:
- mkdocstrings:
    enable_inventory: true
    handlers:
      python:
        paths: [..]
        selection:
          private: true
          protected: true
        options:
          show_signature_annotations: true
- search
- mermaid2:
    version: 10.0.2

nav:
- CLT Toolkit: 
    - index.md
    - math_transitions.md
- MetroFluSim:
    - math_flu_components.md
    - flu_input_requirements.md
- Code API Reference:
    - clt_base_package_reference.md
    - flu_components_reference.md
- Python for Modelers:
    - python_resources.md
theme: 
  name: material 
  favicon: img/favicon.ico
  features:
    - toc.integrate

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.13.13/dist/contrib/auto-render.min.js

